// user action types
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const RESET_REGISTRATION_SUCCESS = "RESET_REGISTRATION_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_USER_SUBSCRIPTIONS = "GET_USER_SUBSCRIPTIONS";
export const GET_USER_SUBSCRIPTION = "GET_USER_SUBSCRIPTION";
export const CHANGE_SUBSCRIPTION_STATUS = "CHANGE_SUBSCRIPTION_STATUS";
export const GET_USER_UPVOTED_POSTS = "GET_USER_UPVOTED_POSTS";
export const GET_USER_DOWNVOTED_POSTS = "GET_USER_DOWNVOTED_POSTS";
export const VOTE_COMMENT = "VOTE_COMMENT";
export const RESET_USER_FORM_ERRORS = "RESET_USER_FORM_ERRORS";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_SUBMITTED_POSTS = "GET_SUBMITTED_POSTS";
export const UPDATE_EMAIL = "UPDATE_EMAIL";

// subzeddit action types
export const CREATE_SUBZEDDIT = "CREATE_SUBZEDDIT";
export const RESET_CREATION_SUCCESS = "RESET_CREATION_SUCCESS";
export const RESET_SUBZEDDIT_FORM_ERRORS = "RESET_SUBZEDDIT_FORM_ERRORS";
export const GET_SUBZEDDITS = "GET_SUBZEDDITS";
export const SUBZEDDIT_DETAIL = "SUBZEDDIT_DETAIL";
export const GET_MOST_POPULAR_DEFAULT = "GET_MOST_POPULAR_DEFAULT";
export const GET_SUBZEDDITS_TITLES = "GET_SUBZEDDITS_TITLES";

// post action types
export const CREATE_POST = "CREATE_POST";
export const GET_POST = "GET_POST";
export const VOTE_POST = "UPVOTE_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";
export const RESET_POST_FORM_ERRORS = "RESET_POST_FORM_ERRORS";

// comment action types
export const POST_COMMENT = "POST_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const RESET_COMMENT_CREATION_FLAG = "RESET_COMMENT_CREATION_FLAG";

// loading types
export const LOADING = "LOADING";
export const END_LOADING = "END_LOADING";
